### ISSUE TITLE
Resolve package name to publish kyubuns/AnimeTask

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#1073]
Hi @starikcetin, could you use another package name so @kyubuns package can be published here? Or you might consider take down yours since kyubuns' is compatible with (Open)UPM now.

I think my case https://github.com/openupm/openupm/issues/877 could help.

**Comment by starikcetin** [comment]
Did they increase the version since the last time I published from my form to OpenUPM? If so, you can follow the steps @favoyang explained in the issue you linked ( #877 ). I am fine with you deleting the YAML file.

Otherwise, it can be a little bit of an issue to overwrite a version that is already published.

Let me know. @laicasaane

**Comment by laicasaane** [comment]
Yes, they did increase the version. The latest is v1.0.2.

> I am fine with you deleting the YAML file.

Thanks, I will do that in your stead.

**Comment by favoyang** [comment]
Merged https://github.com/openupm/openupm/pull/1089
