### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by laicasaane** [openupm/openupm#1094]
Hi @favoyang, I had just increased this [package](https://openupm.com/packages/com.laicasaane.unity-quastatemachine/) version to 1.2.0 about 15 hours ago. This is a new repo so there is no way a pre-existing "1.2.0", I don't know how it could be conflicted.

**Comment by favoyang** [comment]
It looks weird. TLDR; I treat it as an one-time server failure and fixed it manually.

For details, please continue to read...

I found 3 build logs on our pipelines.

![image](https://user-images.githubusercontent.com/125390/87522106-cbe02280-c6b7-11ea-87ec-0e124c374a38.png)

The first failed one is a929bc71a73d0a874f26d0434dcd3056f78b16bf, matched with 1.2.0 tags on your repository. I didn't find another successful build log yet, but the 1.2.0 tarball indeed exists on the server. I also find that the latest tag is still 1.1.0. I guess it can be an edge case that during the publishing process:
- [1]  the tarball and packument are uploaded.
- [2] the change of package latest tag failed for some reason.
- [3] the client query the failed reason, the server finds the tarball exists, so it returns 409 version conflict instead of 500 server error.
- [4] it ends up with a "working" build but failed message.

A better approach is the server treats the whole process as a transaction and reverse the changes, but unfortunately, it doesn't.

I'm working on a significate upgrade for the storage backend of our upm server. It may address part of the unexpected storage write failure of step 4. I will update the process on https://github.com/openupm/openupm/issues/886

**Comment by favoyang** [comment]
Thanks for reporting the issue. I will close it for now.
