### ISSUE TITLE
An unintended directory "Samples" was included

### ISSUE THREAD

**Issue by mob-sakai** [openupm/openupm#1315]
I have released the package with `upm` branch (default) as a git-based url.
Therefore, I want to register the package, based on `upm` branch as well.

### `upm` branch (release branch)

✅  `Samples` directory does not exist.  
✅  `Samples~` directory exists.

https://github.com/mob-sakai/SoftMaskForUGUI

![](https://user-images.githubusercontent.com/12690315/93057929-a1a3e480-f6a9-11ea-955c-52d67d233c09.png)

<br><br><br><br>

### The package contents in OpenUPM

❌  `Samples~` directory does not exist.  
❌  `Samples` directory exist.

https://package.openupm.com:443/com.coffee.softmask-for-ugui/-/com.coffee.softmask-for-ugui-1.0.0-preview.9.tgz

![image](https://user-images.githubusercontent.com/12690315/93059468-b2edf080-f6ab-11ea-8b86-ab4742a066b9.png)

<br><br><br><br>

### `develop` and `master` branches (develop branch)

❌  `Samples~` directory does not exist.  
❌  `Samples` directory exists.  
❌  `Samples.meta` file exists.  
❌  `.gitignore`, `.npmignore` and `.releaserc` files exist.

https://github.com/mob-sakai/SoftMaskForUGUI/tree/develop/Packages/SoftMaskForUGUI

![image](https://user-images.githubusercontent.com/12690315/93059551-d2851900-f6ab-11ea-9f96-b8c248f32584.png)

**Comment by favoyang** [comment]
The reason is that openupm pipelines simply track Git tags. So the Git tag itself needs to be a ready-to-use version (it should be able to import by packman using a Git URL). In your case, you have two versioned tags
- https://github.com/mob-sakai/SoftMaskForUGUI/tree/1.0.0-preview.9, tagged from upm
- https://github.com/mob-sakai/SoftMaskForUGUI/tree/v1.0.0-preview.9, tagged from master/develop

We shall track the first one instead. I've updated the package meta file in https://github.com/openupm/openupm/commit/ebd4b734696db3b86c893619c38f6a2ff7873945 to ignore the tag starts with the letter 'v'.

You can release a new version to trigger a new build to verify it.

**Comment by mob-sakai** [comment]
@favoyang 
OK, I understand!
Thank you for your great work! 👍

**Comment by mob-sakai** [comment]
I created a PR to ignore 'v' tags for my packages.

**Comment by favoyang** [comment]
Merged. Thank you for the quick response.
