### ISSUE TITLE
Middle mouse click scroll doesn't work

### ISSUE THREAD

**Issue by MostHated** [openupm/openupm#1396]
Hey there,
    Trying to use the middle mouse button to click and drag up or down to scroll doesn't seem to be working. I want to say it used to work before, but to be honest, now I can't remember, lol. I am pretty sure that if it wasn't working before, I would have noticed it sooner as I use it quite frequently, especially on pages with long readme's and whatnot. Normally it's not a huge deal, but the normal up and down scroll in general feels.. weird? Almost like it's just a tiny bit slower than a normal page on any other site for some reason. Perhaps it's just me? 

Thanks,
-MH

**Comment by favoyang** [comment]
Hi @MostHated,

Sorry for the inconvenience. I appreciated your taste for UX. A recent refactor / re-layout of the package list and package detail pages caused that. I need a custom scroll component for various reasons, the well-used one is https://github.com/mdbootstrap/perfect-scrollbar. However, it has some drawbacks, including lacking support for middle-click. https://github.com/mdbootstrap/perfect-scrollbar/wiki/Caveats

Because it is a simulation of the OS scrollbar, you will feel slightly different. Perhaps the reason you feel weird about it.

I probably won't fix this. But I will keep this issue open for a few days to evaluate the possibility.

**Comment by MostHated** [comment]
I understand and also appreciate the consideration. While it is not the "end of the world", it certainly does help relieve navigation frustration, especially considering how long some of the pages can potentially become. 

It may sound silly, but having to scroll, scroll, etc, x20 and only end up at 1/8th of the way down the page one might get tired of it quickly as it feels like it is a lot of "work" to try and gain any ground.

**Comment by favoyang** [comment]
Rollbacked to the native scrollbar. It didn't solve the tiny scrollbar thumb issue, at least you can use a mid mouse click scroll or two-finger scroll on a touchpad.

However, as the number of packages grows, lots of potential changes may be related to the scrolling experience, like paginations, pull-to-refresh, reusable list cell... I will try to keep the native scrollbar, but sometimes it's a trade-off.

Again, thanks for taking care of the UX.
