### ISSUE TITLE
Trouble with scoped registries

### ISSUE THREAD

**Issue by StephenHodgson** [openupm/openupm#1510]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [x] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [x] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce

1. Add open upm as a registry to the Unity Editor

```
  "scopedRegistries": [
    {
      "name": "Open UPM",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.openupm"
      ]
    }
  ],
```

![image](https://user-images.githubusercontent.com/13334553/96660421-50b58a80-12fe-11eb-810f-006bafb04b85.png)

2. Add an additional scope for `com.halodi`
3. Open the Package Manager window and select `My Registries` from the dropdown

![image](https://user-images.githubusercontent.com/13334553/96661029-01705980-1300-11eb-8b4c-4b554a18a75d.png)

the halodi packages don't show up under the same registry.

#### What is expected?

Packages show up under the same registry

#### What is actually happening?

Packages show up under different registries

#### Other relevant information

Tested using Unity 2019.4.12f1

**Comment by StephenHodgson** [comment]
I'm guessing that the real reason is bc the project.json is missing the author information:

```
{
  "name": "com.halodi.halodi-unity-package-creator",
  "version": "0.2.9",
  "displayName": "Halodi Unity Package Creator",
  "description": "Tools for creating, editing and publishing Unity packages",
  "unity": "2019.3",
  "repository": {
    "type": "git",
    "url": "https://github.com/Halodi/halodi-unity-package-creator.git"
  },
  "license": "Apache-2.0",
  "author": {
    "name": "Jesper Smith",
    "email": "jesper@halodi.com",
    "url": "http://www.halodi.com"
  },
  "keywords": [],
  "dependencies": {
    "com.halodi.halodi-unity-package-registry-manager": "0.1.2"
  },
  "publishConfig": {
    "registry": "https://package.openupm.com"
  },
  "type": "tool"
}
```
vs
```
{
  "name": "com.halodi.halodi-unity-package-registry-manager",
  "version": "0.1.2",
  "displayName": "Halodi Unity Package Registry Manager",
  "type": "tool",
  "samples": [],
  "description": "Simple tool to manage scoped registries and NPM credentials.",
  "license": "Apache-2.0",
  "publishConfig": {
    "registry": "https://package.openupm.com"
  }
}
```

**Comment by favoyang** [comment]
Yes, the "My Registries" doesn't group packages by the registry, but by the author. Packages missing the author field are categoreized into the `Other` section.

**Comment by StephenHodgson** [comment]
So is there a way to update the author section of the package in openupm?

I noticed that there's quite a few authors who's packages don't show up when adding their scopes, and a few packages that wouldn't show up at all, (like Mob-Sakai)

**Comment by favoyang** [comment]
I'd like to leave that to the author to minimize the changes to the package.json during publishing. Though I could fill the name from the GitHub user display name, it's mutable which may bring more troubles, and it's only limited to the GitHub user.

What I can do is creating a suggestion tab on the package detail page to warn the author to make the metadata better.

To be honest, I don't get why it's necessary to group by author name in "My Registries", isn't it should be group by registry instead?

**Comment by favoyang** [comment]
> a few packages that wouldn't show up at all, (like Mob-Sakai)

Could you give me one example package full name, and the scopes you specified in manifest.json to verify?

**Comment by StephenHodgson** [comment]
> To be honest, I don't get why it's necessary to group by author name in "My Registries", isn't it should be group by registry instead?

That's what I was thinking. Maybe it's something in Unity that they're doing silly 🤷‍♂️ (also wouldn't surprise me)

I tried:
`com.openupm` (I believe this is required to get any other scopes)
`com.baba-s` since they have the most packages hosted on OpenUPM
`com.xrtk` since it's mine haha
`com.coffee` aka @mob-sakai cause they rock ❤️

**Comment by favoyang** [comment]
The scope `com.openupm` will add nothing for now. Because no packages were published under this scope. It was added when you installed any package via OpenUPM-CLI.

The scope `com.baba-s` will add nothing for now. Though baba-s has more than 200 pending packages listed on the OpenUPM website. None of them are available to use. Because none of these repositories do version control via Git tags. We need to find time to talk about how we can bring these packages into the platform without too much work added to the package owner.

The scope `com.xrtk` will add below under the "My Registries" section.

![image](https://user-images.githubusercontent.com/125390/96888830-9cac2f00-14b8-11eb-8725-0dff69309a71.png)

There are more searchable packages on the OpenUPM website. The missing ones are lacking valid Git tags (the same reason as the baba-s' packages).

![image](https://user-images.githubusercontent.com/125390/96888729-82725100-14b8-11eb-9531-8938f8afd5a4.png)

The scope `com.coffee` will add below under the "My Registries" section. If you didn't see them you need to click the refresh button > refresh list.

![image](https://user-images.githubusercontent.com/125390/96889499-3a9ff980-14b9-11eb-9ac4-ef2de896ba50.png)

Anyway, it works for me.

When you added a scope name, The PackMan will call a `/search` endpoint on the registry server to collect package meta information. If the search endpoint is not supported it will fallback to call the `/all` endpoint to get all package lists. Then the PackMan constructs a package list in the memory. If you search anything in the search input box, it gonna search the local data and limited to the scopes you provided (even it knows all packages from the '/all` endpoint). It won't fetch the network again unless you hit the refresh button. That means you can not search for a package without telling the PackMan the scope in advance.

**Comment by StephenHodgson** [comment]
Yeah, `com.coffee` still has one listed under `Other` 🙁

**Comment by mob-sakai** [comment]
Hi, since I've been mentioned, let me answer your question.
The package `UI Gradients` is **not my package.**
According to OpenUPM, the repository owner is @Sov3rain.
https://openupm.com/packages/com.coffee.uigradients/
https://github.com/Sov3rain/Unity-UIGradient

**Comment by StephenHodgson** [comment]
Yeah but I think it still falls under your scope. `com.coffee`

**Comment by StephenHodgson** [comment]
Linking the other issues for reference https://github.com/Halodi/halodi-unity-package-registry-manager/pull/2

**Comment by hybridherbst** [comment]
@favoyang checking for proper author information was one of my earlier suggestions for additional OpenUPM checks on adding packages, along with checking that package names are well-scoped (e.g. no packages that just have scope "mypackage" or "myname.mypackage").

@StephenHodgson as you have correctly found PackMan groups by author, not by registry, which is actually a good thing: it groups packages much more logically - e.g. we have some packages on OpenUPM, some on our own registry(s), and some locally embedded in projects, and they get grouped together under the correct author name.

That being said, the PackMan team could do a much better job at showing registry information.

In our our package tooling, we use package Tags to properly communicate registry information, which works great:
![image (1)](https://user-images.githubusercontent.com/2693840/97083004-c32fae80-160d-11eb-98a0-c2a5fa710837.png)

As mentioned elsewhere the plan is to release that somewhat soon (including auth, access to OpenUPM, package deeplink installation), plus we're in discussions with Unity on what they can do to improve this.

**Comment by StephenHodgson** [comment]
@hybridherbst  yeah that UI is looking super good 🤩

Is that package tooling available publicly? 😅

**Comment by favoyang** [comment]
> @favoyang checking for proper author information was one of my earlier suggestions for additional OpenUPM checks on adding packages, along with checking that package names are well-scoped (e.g. no packages that just have scope "mypackage" or "myname.mypackage").

Tracked as https://github.com/openupm/openupm/issues/1521

**Comment by favoyang** [comment]
> What I can do is creating a suggestion tab on the package detail page to warn the author to make the metadata better.

Tracked as #1523

**Comment by favoyang** [comment]
Split the feature request to #1521 and #1523. This issue is closed.
