### ISSUE TITLE
Unpublished new package

### ISSUE THREAD

**Issue by sebas77** [openupm/openupm#1557]
Hi,

just checking that everything is all right. I published a new package from the website and I am wondering how the moderation works as I can see very old packages still unpublished there.

**Comment by favoyang** [comment]
Hi,

The unpublish policy is described here: https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version

When you create an issue, you can choose from two related [issue templates](https://github.com/openupm/openupm/issues/new/choose) to ask for unpublishing a version and purging a package entirely. As said in the documentation, not a recommendation. But sometimes people do have a reason to do so, then you need to fill the issue to explain and we will help (so far manually).

**Comment by sebas77** [comment]
Forgive me, I have been confusing with my question, but this is not what I have asked.

What I have asked is this:

I use the form to publish a new package that is not public yet. I am not sure who moderate the inclusion of a new package and why there are some packages pending that are weeks old. My new package is this:

https://openupm.com/packages/System.Runtime.CompilerServices.Unsafe.dll/

**Comment by favoyang** [comment]
I see. The pending state means the package didn't have at least one version available to use. The common reasons are missing valid Git tags, or all tags are failed to build. The package you mentioned has no valid Git tags. You need to create a Github release and name it with x.y.z or vx.y.z, to match with your package.json version. After you create the new tags, our pipelines typically publish a new version within 10mins.

![image](https://user-images.githubusercontent.com/125390/97868649-07782880-1d4b-11eb-847b-f4dd143f16a3.jpeg)

The installation box tells the same.

If anything goes wrong, you can check the pipelines tab for reasons.

OpenUPM is a loosely community to discover open source UPM packages. People may submit packages they like, but without version control (non Git tags). Or they pushed for that, but the author didn't response yet. That's why we have quite a few "old" packages in the pending state. We could make that process less painful, by providing tools/templates to help package hunter create issues on the original repo. But I haven't get enough time to work on it.

**Comment by sebas77** [comment]
thank you
