### ISSUE TITLE
Should validate yml file path when it is submitted to CI

### ISSUE THREAD

**Issue by grashaar** [openupm/openupm#1665]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [x] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
1. Remove `.yml` extension from any yml file name
2. Commit and make a PR
3. Wait for the CI to complete

#### What is expected?
The CI pipeline should fail and print a message telling that the file path is incorrect.
OR the CI will automatically append the missing extension to the file name.

#### What is actually happening?
The CI completed successfully.

#### Other relevant information
I've just found it out after https://github.com/openupm/openupm/pull/1662/ was merged and I can't find the package on openpum website.

**Comment by favoyang** [comment]
Thanks for reporting the issue. Just added the missing extension name.

The merge bot actually ignored the PR: https://github.com/openupm/openupm/runs/1466804202 because the file added is missing the `.yml`. I made the mistake to merge it manually.

But I agree that the CI could be better just reject it explicitly.

**Comment by favoyang** [comment]
The extra CI test was added in 89845ee

And your package is available at: https://openupm.com/packages/com.grashaar.unity-google-spreadsheet-downloader/?subPage=pipelines
