### ISSUE TITLE
Don't open links in a new tab

### ISSUE THREAD

**Issue by andybak** [openupm/openupm#228]
That should be a user choice. Don't modify normal link behaviour. 

You're dealing with a tech-savvy audience. They know how to open a link in a new tab if they *choose* to. Changing standard behaviour just means I've got to go back and close the first window if I didn't want to open in a new tab.

https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

https://www.sitepoint.com/beware-opening-links-new-window/

https://ux.stackexchange.com/questions/31579/when-if-ever-should-links-be-opened-in-a-new-window

**Comment by favoyang** [comment]
Agreed. I think external links are handled automatically by vuepress, with a outline link icon rendered next to it. But I will check the behavior later.

**Comment by andybak** [comment]
OK. I'll file an issue with Vuepress as well then. It shouldn't be their default behaviour for external links. (I've been bickering with clients for a couple of decades over this and really thought it was a battle we'd finally won. Sigh...) 

Thanks!

**Comment by favoyang** [comment]
@andybak I confirm that the behavior is caused by VuePress [NavLink](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/NavLink.vue), a fundamental template tag used everywhere.

I have changed want I can do, with two exceptions.
- The GitHub link at the homepage top right is rendered by Vuepress itself, which is hard to change.
- The new package destination link at the package submission page is intended to be opened in a new window for a few tech reasons. Well, for time reason, I'm not going to cover the details here.
