### ISSUE TITLE
Package page is reverted to an old commit

### ISSUE THREAD

**Issue by grashaar** [openupm/openupm#245]
I don't know why but after a while the page of [UIMan](https://openupm.com/packages/com.minhdu.uiman/) has been reverted to a very old version of README.

**Comment by favoyang** [comment]
@grashaar, thanks for reporting the issue. Since a recent update, you need to specify the README path if it's not located at master:README.md. The issue has been fixed in https://github.com/openupm/openupm/commit/a294c2642dfa124d5a4b07f9e0a2265d28dc4e21, but it will take up to 30mins to fresh the cache.
