### ISSUE TITLE
com.wooshii.hierarchydecorator v0.8.5 is missing

### ISSUE THREAD

**Issue by Razenpok** [openupm/openupm#2927]
## Bug report

com.wooshii.hierarchydecorator package is missing the 0.8.5 version. It can be found in [Build Pipelines](https://openupm.com/packages/com.wooshii.hierarchydecorator/?subPage=pipelines), but not in [Versions](https://openupm.com/packages/com.wooshii.hierarchydecorator/?subPage=versions)

#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [x] Pipelines: issues related to publish or manage a package.
- [x] Registry: issues related to the registry server.
- [ ] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

**Comment by favoyang** [comment]
Hi @Razenpok,

The problem is that the Git tag is mismatched with package.json version.

Tag 0.8.5, package.json 0.8.4 https://github.com/WooshiiDev/HierarchyDecorator/blob/f10ba2593ca24ffead8e2184c052f24f388c4064/package.json

Tag 0.8.4, package.json 0.8.3 https://github.com/WooshiiDev/HierarchyDecorator/blob/57c0d1b1ffff692ccd4095bdbb306a3cfbb0154f/package.json

Perhaps your CI could bump package.json version first, then create the Git tag?

You can align your Git tag and package.json version with 0.8.6 to fix the issue.

OpenUPM build pipeline section didn't show the actual published version, it just shows the version parsed from the Git tag. Something to improve for us.

**Comment by Razenpok** [comment]
Ok, I'll contact the package author

Thanks for such a quick response!
