### ISSUE TITLE
(UnityEditor) Install packages using UI

### ISSUE THREAD

**Issue by mob-sakai** [openupm/openupm#3054]
#### Feature category

- [ ] Website: improve the way to browse or discover packages.
- [ ] Pipelines: improve the way to publish or manage a package.
- [ ] Registry: improve the registry server.
- [x] Unity Editor: improve how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### How should this be implemented in your opinion?

![image](https://user-images.githubusercontent.com/12690315/170185668-0ed2fdcd-67b3-4e82-9f9c-8d19a05ee879.png)

#### Are you a regular backer or sponsor at [patreon.com/openupm](https://www.patreon.com/openupm)?

No

#### Are you willing to work on this yourself?

Yes

**Comment by favoyang** [comment]
Hi @mob-sakai,

Is this a plugin you're working on? Have you noticed the terms have banned such practice?

https://unity3d.com/legal/terms-of-service/software/package-guidelines

> D. You cannot harm or mislead users.  For example:
> - You add, update or modify installed Packages on behalf of the user outside the official Unity Editor UI, such as programmatically through scripts.

Even writing a script to notify users of package version updates is considered breaking the terms. 🤐

Well, I really like your idea, but it can not be part of the official OpenUPM product. Sorry for the inconvenience.

**Comment by favoyang** [comment]
I understand your feeling and you're not alone here.

- https://github.com/openupm/openupm/discussions/10#discussioncomment-226467 (the old issue you submit for the in-editor package list)
- https://github.com/openupm/openupm/discussions/2841#discussioncomment-2295297 (the rejection for the in-editor package update notification)
- https://github.com/firebase/quickstart-unity/issues/1030#issuecomment-826249998 and https://github.com/openupm/openupm/pull/3021#issuecomment-1133139003 (the rejection for google firebase)
- The ban of [package installer](https://package-installer.glitch.me/)

Unity certainly doesn't have the energy to verify every package on OpenUPM or GitHub. OpenUPM is operating for 2.5 yrs, I didn't receive a single request from Unity for a specific package's TOS issue. Well, we used to have some conversations about the general TOS adoption and the result has been recorded in https://github.com/openupm/openupm/discussions/1731. After that, we don't talk anymore. It works in a self-censorship way. I try my best to point out the TOS issue, and let developers decide for themselves.

It is always a case-by-case thing. For example, your famous https://github.com/mob-sakai/UpmGitExtension is a package hosting on GitHub that leverages the Unity Editor as a distribution platform for Packages to third parties. But it is survived AFAIK. Maybe because that package is operating other GitHub repositories, not a scoped registry? Who knows. I am certainly not a lawyer to tell what can be done, or what can not be based on their broad guideline text.

Sorry again for writing these for a developer who wants to contribute to OpenUPM and benefit Unity's interests more or less.
