### ISSUE TITLE
Timeout error: [Package Manager Window] connect ETIMEDOUT

### ISSUE THREAD

**Issue by jacattrongnlh** [openupm/openupm#3403]
#### Bug category

- [ ] Website: issues related to browse or discover packages.
- [ ] Pipelines: issues related to publish or manage a package.
- [ ] Registry: issues related to the registry server.
- [X] Unity Editor: issues related to how OpenUPM works with the Unity Editor.
- [ ] Documentation
- [ ] Others

#### Steps to reproduce
I follow the step to manually install package at https://openupm.com/packages/com.omnilatent.litjson/?subPage=readme#modal-manualinstallation

> Please follow the instrustions:
> 
> open Edit/Project Settings/Package Manager
> add a new Scoped Registry (or edit the existing OpenUPM entry)
> Name package.openupm.com
> URL https://package.openupm.com
> Scope(s) com.omnilatent.litjson
> click Save (or Apply)
> open Window/Package Manager
> click +
> select Add package by name... (option not available) or Add package from git URL...
> paste com.omnilatent.litjson into name
> paste 1.0.1 into version >>> This step cannot be done, I don't see any version field
> click Add

#### What is expected?
The package is installed successfully.

#### What is actually happening?
The Package Manager load for a long time and then it logs these errors to Console.

```
[Package Manager Window] connect ETIMEDOUT 205.185.216.10:443
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)

[Package Manager Window] Cannot perform upm operation: connect ETIMEDOUT 205.185.216.10:443 [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)

[Package Manager Window] Error adding package: com.omnilatent.litjson.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)
```

#### Other relevant information
Unity Editor version: 2020.3.18

**Comment by favoyang** [comment]
> connect ETIMEDOUT 205.185.216.10:443

The message means your network can not reach to one of the CDN servers when fetching package tarball.

If the request is from China mainland, you can switch to the CN region (by changing package.openupm.com to package.openupm.cn). Otherwise, you can verify your network with URL https://openupm.sfo2.cdn.digitaloceanspaces.com, it should work and returns you an XML file.

>paste 1.0.1 into version >>> This step cannot be done, I don't see any version field

The version field is only available for Unity 2021 and later.

**Comment by jacattrongnlh** [comment]
I got this error after opening the link. I'm not in China.
```
<Error>
<Code>AccessDenied</Code>
<BucketName>openupm</BucketName>
<RequestId>tx00000000000013107b64f-00633fcf11-3ade2f46-sfo2a</RequestId>
<HostId>3ade2f46-sfo2a-sfo</HostId>
</Error>
```

**Comment by favoyang** [comment]
It's the expected response, which means you can access to our tarball server in your browser without any issues.

The actual tarball is located at https://package.openupm.com/com.omnilatent.litjson/-/com.omnilatent.litjson-1.0.1.tgz, in case you want to double-check.

Is there any chance you're using a proxy that may block network access? or any HTTP_PROXY settings?

Could you download a recent version of Unity 2021 or later to reproduce the issue?

**Comment by favoyang** [comment]
BTW, I have just installed the package without any issues using Unity 2021 or 2022.

**Comment by jacattrongnlh** [comment]
> The actual tarball is located at https://package.openupm.com/com.omnilatent.litjson/-/com.omnilatent.litjson-1.0.1.tgz, in case you want to double-check.

It took about 30 seconds of loading before I see the download prompt. The file can be downloaded using web browser. Another thing to note is when I open https://openupm.sfo2.cdn.digitaloceanspaces.com/, it took more than 2 minutes before I see a response.

> Is there any chance you're using a proxy that may block network access? or any HTTP_PROXY settings?
No I do not use proxy. I'm from Vietnam. Could it be connection from here to openupm's server is too slow?

**Comment by favoyang** [comment]
That's indeed abnormal. It's either a slow DNS resolution or a slow connection from your location to the server.

The DNS query should return instantly.
```
# mac/linux
host openupm.sfo2.cdn.digitaloceanspaces.com

# windows 
nslookup openupm.sfo2.cdn.digitaloceanspaces.com
```

I checked four Asia locations (Tokyo, Seoul, Mumbai, and Singapore), and they all work fine against openupm.sfo2.cdn.digitaloceanspaces.com. The tarball is only 40 kb, it's been downloaded instantly. But I don't have a Vietnam infrastructure to test.

**Comment by favoyang** [comment]
BTW, the geotargetly service shows me almost immediately a screenshot of https://openupm.sfo2.cdn.digitaloceanspaces.com from a Vietnam infrastructure.

https://geotargetly.com/geo-browse?url=https://openupm.sfo2.cdn.digitaloceanspaces.com&country_code=VN

**Comment by jacattrongnlh** [comment]
I asked my coworker to open the URL, he can load the page https://openupm.sfo2.cdn.digitaloceanspaces.com/ instantly. But when he install the com.omnilatent.litjson package using openupm, he gets the same Timeout error as me.

Then I tried using Netherland VPN and I've been able to install the com.omnilatent.litjson package using openupm in Unity. While it's a workaround, I wouldn't put that into our workflow, VPN is slow and expensive. I hope we can find out what's wrong that prevent me from using openupm normally.

**Comment by favoyang** [comment]
> I asked my coworker to open the URL, he can load the page https://openupm.sfo2.cdn.digitaloceanspaces.com/ instantly. But when he install the com.omnilatent.litjson package using openupm, he gets the same Timeout error as me.

From the same network or a different location from your city/country?

AFAIK, the server of openupm.sfo2.cdn.digitaloceanspaces.com is currently located in Dalla, Texas, US.

```
openupm.sfo2.cdn.digitaloceanspaces.com is an alias for cds.b5g9b8e4.hwcdn.net.
cds.b5g9b8e4.hwcdn.net has address 205.185.216.42
cds.b5g9b8e4.hwcdn.net has address 205.185.216.10
```

Since I have tested a few Asia cities without any issues. I have to assume that it's a problem from your/your coworker's network to the CDN server. Perhaps a general network for Vietnam to reach our data center.

Debugging a specific network issue is out of my scope, I also don't have a Vietnam machine to test it. But here are some common tips,
- Try the DNS query above and share the result, to eliminate the DNS resolution issue. It should return instantly.
- Try some traceroute to detect the potential network issue: traceroute, mtr (winmtr)...
- Test from different locations, home, office...

I also contacted my cloud vendor to see if they have detected any issues with Vietnam users.

**Comment by favoyang** [comment]
> But the information didn't help much unless you spend more energy to route trace.

i.e. using mtr (or winmtr for windows) may give you some hits about the route path.

```
mtr -rwc 15 openupm.sfo2.cdn.digitaloceanspaces.com
```

**Comment by jacattrongnlh** [comment]
I ran the command and I got: 
```
[my local IP, my ISP, local host...]
  8.|-- localhost                            0.0%    15    5.3   3.5   2.9   5.3   0.6
  9.|-- ae-3.r03.tkokhk01.hk.bb.gin.ntt.net  0.0%    15   23.6  23.5  22.7  24.8   0.6
 10.|-- 151.139.58.3                         0.0%    15   23.2  22.6  21.9  24.4   0.7
 11.|-- 100.65.15.47                         0.0%    15   24.7  22.6  21.8  24.7   0.7
 12.|-- map2.hwcdn.net                       0.0%    15   21.8  21.8  21.4  22.4   0.3
```

Strangely though, today, I changed nothing but it worked. My coworker and I can install com.omnilatent.litjson using openupm without issues.

**Comment by favoyang** [comment]
The last two IPs show the traffic has been routed to HK. You can use the command to trace the route next time if there are any issues. For now, we don't know if it's problem with your ISP or the anycast router.

Unfortunately, for an anycast IP, the client side can not force to pick a geo node. There's nothing we can do to deal with it.

Anyway, glad to see the problem is gone.
