### ISSUE TITLE
Unpublish the package com.leaosoft.gameplay.framework

### ISSUE THREAD

**Issue by WendellLeao** [openupm/openupm#3445]
Please read the guideline for [unpublishing a package](https://openupm.com/docs/modifying-upm-package.html#unpublishing-a-package) first.

#### What's the reason to unpublish the package entirely?

I messed up all the tags and the git commit history is a real mess. I've published this package yesterday (10/10/2022), I'm sure no one has use it yet. I want to unpublish this package entirely, then I would publish a new one and handle its updates properly.

#### What's the package name?

com.leaosoft.gameplay.framework

#### Have you removed the package meta file and added the package name to the blocked-scopes.yml?

I've removed the package meta file, but I couldn't add the package name to the blocked-scopes.yml.

**Comment by favoyang** [comment]
`com.leaosoft.gameplay.framework` has been removed from the openupm registry.

The website page will be removed once #3446 gets fully merged (about 30 minutes later).


> I've removed the package meta file, but I couldn't add the package name to the blocked-scopes.yml.

That PR needs a review. In this case, you don't need to update the blocked scopes since you're intended to choose a new package name soon.
