### ISSUE TITLE
Update a package version

### ISSUE THREAD

**Issue by arthur740212** [openupm/openupm#4043]
#### What's the package name?
com.playeveryware.eos `v2.3.0`

#### The reason to update the package?

The old `v2.3.0` tag is made on a commit with some bugs breaking lfs.
The tag is now moved to the next commit that fixes the issue

**Comment by favoyang** [comment]
I have removed v2.3.0 from the registry. However, the tag v2.3.0 is still listed on https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/tags (created 3 weeks ago), our pipeline will catch up and build it again.

I'm not sure your mean by

> The tag is now moved to the next commit that fixes the issue

If the tag created 3 weeks ago [ba6536f](https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/commit/ba6536f2c392151b540ef52f63701bca81f3d2bf) is the fixed one, then we're good here.

Otherwise, please remove that tag, I will unpublish v2.3.0 again.

**Comment by favoyang** [comment]
Anyway, your case is trivial, and I suggest you publish a new version to fix it in the future.

**Comment by arthur740212** [comment]
Oops, we moved the tag on the wrong repo, let us try this again

**Comment by favoyang** [comment]
> Oops, we moved the tag on the wrong repo, let us try this again

I tried again, but the tag [v2.3.0](https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/releases/tag/v2.3.0) is still there based on [ba6536f](https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/commit/ba6536f2c392151b540ef52f63701bca81f3d2bf).

In your case, please bump a version to publish a fix. Even if I could assist you once again, to let you re-publish that version, it worse for your client who already installed that version. They will not get an update prompt from the Unity package manager and they will get stuck on that version until the next release.
