### ISSUE TITLE
Republish package version

### ISSUE THREAD

**Issue by kantagara** [openupm/openupm#4422]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
Because I want to add the same version with some crucial bugfixes so that I don't have to bounce it up to 2.5.3
#### What's the package name?
io.chainsafe.web3-unity
#### Which version(s) you want to unpublish?
2.5.2
#### Have you removed or replaced the related Git tag(s)?
I have replaced tag io.chainsafe.web3-unity/2.5.2 in our repository, name is the same but it is pointing to another commit now.

**Comment by favoyang** [comment]
@kantagara,

Does your case fall into any of these categories?

- The version inadvertently leaks security information, such as accidentally committing a private key and publishing it.
- The version contains harmful content that may endanger the developers who install it.
- The version violates our package guidelines.

Please be more specific about it. Otherwise, the issue will be rejected due to our policy described in https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version

**Comment by kantagara** [comment]
Hello @favoyang the issue is kinda the same as this one
https://github.com/openupm/openupm/issues/4276
And it's even the same repo.
I would say that the version contains harmful content (i.e. bugs, and errors), that may endanger the developers who install it (it won't break their PC, but the package would be completely unusable).

**Comment by favoyang** [comment]
Hi @kantagara,

I'm afraid that #4276 is an offer for a new package that was published less than 72 hours ago.

In your case, to address bugs/errors that render your package completely unusable — for instance, a compile error — you should increment the version number to fix it. This step is important because, as described in the documentation, there are multiple layers of cache, including CDN, inter-proxy servers, and Unity's local cache. Be aware that updating on our server does not guarantee that these caches will be cleared. This might lead to more complex issues.

Ideally, you could deprecate that version. However, since the Unity Editor does not recognize deprecation, incrementing the version number is the required action to implement a fix.

**Comment by favoyang** [comment]
@kantagara,

Please note that the best way to update the version is to directly change it to 2.5.3. Using a "suffix", which is essentially a pre-release tag, to alter your version to 2.5.2-hotfix.1 is ineffective. This is because, in semantic versioning, a pre-release is always considered less than a regular release (2.5.2-hotfix.1 < 2.5.2 < 2.5.3).

For more information, you can refer to this Semantic Versioning Comparison: https://semvercompare.azurewebsites.net/?version=2.5.2-hotfix.1&version=2.5.2&version=1.0.0&version=2.5.3
