### ISSUE TITLE
Unpublish package version

### ISSUE THREAD

**Issue by Sabu006** [openupm/openupm#4815]
Please read the guideline for [unpublishing a package version](https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version) first.

#### What's the reason to unpublish a version?
All versions violate Unity's package guidelines.

#### What's the package name?
tech.uslog.eauploader

#### Which version(s) you want to unpublish?
All versions from 0.9.4 to 0.9.94

#### Have you removed or replaced the related Git tag(s)?
Yes.

**Comment by favoyang** [comment]
I removed these versions:

```
0.9.94	
0.9.93	
0.9.92	
0.9.9	
0.9.83	
0.9.797
0.9.796	
0.9.795	
0.9.794	
0.9.793	
0.9.792	
0.9.82	
0.9.79	
0.9.78	
0.9.77	
0.9.76	
0.9.75	
0.9.74	
0.9.72	
0.9.8	
0.9.7	
0.9.5	
0.9.4	
```

I also removed related [build logs](https://openupm.com/packages/tech.uslog.eauploader/?subPage=pipelines) except for the below tags, because you didn't remove these Git tags yet.

```
0.9.94	
0.9.93	
0.9.92	
0.9.9	
```

Now the `0.9.95` is the only [published version](https://openupm.com/packages/tech.uslog.eauploader/?subPage=versions).

Notice that the '0.9.96` Git tag is built and failed with a trivial version conflict error.
