### ISSUE TITLE
Shows stars of original repo and not stars of fork

### ISSUE THREAD

**Issue by jilleJr** [openupm/openupm#525]
## Expected

My package shows ⭐ 171 stars, since my package has 171 stars

![stars of jilleJr/Newtonsoft.Json-for-Unity](https://user-images.githubusercontent.com/2477952/82729961-75301b00-9cfc-11ea-9ad4-4642a6f50314.png)

## Actual

My package shows ⭐ 7993 stars

![OpenUPM details panel for jillejr.newtonsoft-for-unity](https://user-images.githubusercontent.com/2477952/82729944-4023c880-9cfc-11ea-8d44-2682c8bf55d4.png)
(https://openupm.com/packages/jillejr.newtonsoft.json-for-unity/)

since James repo has 7993 stars:

![stars of JamesNK/Newtonsoft.Json](https://user-images.githubusercontent.com/2477952/82729949-4d40b780-9cfc-11ea-8867-9c16e213adff.png)

## Suggested solution

Viewing the stars of the original project is good, but I think it may be misleading. I suggest instead to view both star counts for extra clarity in cases of forked repos.

For example:

![image](https://user-images.githubusercontent.com/2477952/82730138-defcf480-9cfd-11ea-9253-b61de8724f10.png)

Or perhaps flipped:

![image](https://user-images.githubusercontent.com/2477952/82730155-f63be200-9cfd-11ea-8f8c-1de79534ba86.png)

**Comment by jilleJr** [comment]
I would actually like to attempt adding a PR on this :) 
Never worked with Vue before and I'd like to think it would be a great experience.

What's your thoughts on the suggested solutions?

**Comment by favoyang** [comment]
Hey @jilleJr,

I'm okay with showing the actual stars instead of the sum, it probably just more fair. But noticed that it will be consistent across the whole website.
- Package detail page
- Package card on the lister page (affects sort by popularity)

I took your first suggestion and changed the text to "upstream". Sorry that I didn't notice that you want to contribute a PR. There will be many chances. Stay tuned.

**Comment by jilleJr** [comment]
Cool cool! And np ✌
