### ISSUE TITLE
feature request: Docker container

### ISSUE THREAD

**Issue by mystikxkemix** [openupm/openupm#54]
Is it possible to have a Docker container available on the Docker Hub?
It would improve the way to update / deploy OpenUPM

**Comment by favoyang** [comment]
@mystikxkemix 

Thanks for requesting the feature. For now the application is manually deployed to digital ocean servers using ansible. The project is a combination of [micro services](https://openupm.com/docs/dev/#architecture),
- updates of the docs, packages will trigger the netlify deployment.
- updates of build pipelines, the http API will trigger the GtiHub actions, then deploy to our server.
- the registry is managed manually.

So speaking of the continuous deployment, it already did. It just not that as sexy as a Docker container. 

Because it's a central service, not a tool that everyone wanner deploy to their own box. And I think our server infrastructure is not very stable, so for now I would like to keep the current way for a while.  It's a good issue, I will record this to my backlog, but in a lower priority.
